name: Build Wheels

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Cuda Toolkit
        uses: Jimver/cuda-toolkit@v0.2.10
        with:
          cuda: '11.8.0'
        
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Install dependencies
        run: |
          conda env update --file 'https://github.com/0cc4m/KoboldAI/raw/latestgptq/environments/huggingface.yml'
          python -m pip install build

      - name: Build wheels
        run: python -m build -n --wheel

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
